const profilesList = [
  {
    id: 1,
    nom: "le Grand",
    prenom: "Thibaut",
    titre: "Chevalier de la Taverne",
    age: 32,
    race: "Humain",
    classe_sociale: "Noble",
    sexe: "Masculin",
    localisation: "Forteresse des Brumes",
    metier: "Chevalier errant",
    attirance: "Humains/Féminin",
    interets: "Joutes verbales, Chasse aux dragons, Tournois",
    description:
      "À la recherche d'une dame à sauver (ou d'une pinte à partager).",
    photos: ["thibaut1.jpg", "thibaut2.jpg"],
  },
  {
    id: 2,
    nom: "la Sorcière",
    prenom: "Morgane",
    titre: "Mystique des Bois",
    age: 28,
    race: "Humain",
    classe_sociale: "Monstre",
    sexe: "Féminin",
    localisation: "Forêt Enchantée",
    metier: "Herboriste",
    attirance: "Humains/Non-binaire",
    interets:
      "Fabrication de potions, Récolte d'herbes magiques, Enchantements",
    description:
      "Herboriste à la recherche d'une âme sœur pour concocter des potions d'amour.",
    photos: ["morgane1.jpg", "morgane2.jpg"],
  },
  {
    id: 3,
    nom: "le Fort",
    prenom: "Bjorn",
    titre: "Guerrier du Nord",
    age: 40,
    race: "Humain",
    classe_sociale: "Noble",
    sexe: "Masculin",
    localisation: "Citadelle du Nord",
    metier: "Forgeron",
    attirance: "Humains/Féminin",
    interets: "Forge d'armes, Expéditions vikings, Festins",
    description:
      "Forgeron robuste cherchant à forger des liens aussi forts que l'acier.",
    photos: ["bjorn1.jpg", "bjorn2.jpg"],
  },
  {
    id: 4,
    nom: "du Bois",
    prenom: "Elowen",
    titre: "Gardienne des Arbres",
    age: 150,
    race: "Elfe",
    classe_sociale: "Noble",
    sexe: "Féminin",
    localisation: "Forêt de Lumière",
    metier: "Protectrice de la Nature",
    attirance: "Elfes/Masculin",
    interets: "Chant des arbres, Soins aux animaux, Protection de la forêt",
    description:
      "Élue de la forêt, cherche compagnon pour veiller sur la nature.",
    photos: ["elowen1.jpg", "elowen2.jpg"],
  },
  {
    id: 5,
    nom: "le Troubadour",
    prenom: "Robin",
    titre: "Barde Errant",
    age: 25,
    race: "Humain",
    classe_sociale: "Paysans",
    sexe: "Masculin",
    localisation: "Village de l'Aube",
    metier: "Barde",
    attirance: "Humains/Féminin",
    interets: "Musique, Contes, Banquets",
    description:
      "Chanteur de ballades à la recherche d'une muse pour de nouvelles chansons.",
    photos: ["robin1.jpg", "robin2.jpg"],
  },
];

export default profilesList;
